#!/usr/bin/env python3
"""Regenerates persistence/aaf/AafDictionaryData.cpp.

Every AAF file carries the standard MetaDictionary (class, property and type
definitions) and Dictionary (data, container, codec ... definitions). Rather
than hand-write hundreds of definitions, Beat Maker embeds the ones a pyaaf2
(MIT) reference file contains, as gzip'd CFB nodes, plus that file's
"referenced properties" table (which the weak references in both subtrees
index into: 0 ClassDefinitions, 1 TypeDefinitions, 2 DataDefinitions,
3 ContainerDefinitions; AafWriter.h's RefPath must match).

Usage:  python3 -m venv venv && venv/bin/pip install pyaaf2
        venv/bin/python tools/gen_aaf_dictionary.py
"""
import gzip, os, struct, sys, tempfile
import aaf2

repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dest = os.path.join(repo, "persistence", "aaf", "AafDictionaryData.cpp")
ref = os.path.join(tempfile.gettempdir(), "beatmaker_aaf_reference.aaf")

# A reference file that uses the sound, timecode and descriptive-metadata data
# definitions and the AAF and External container definitions.
with aaf2.open(ref, "w") as f:
    comp = f.create.CompositionMob("reference"); f.content.mobs.append(comp)
    src = f.create.SourceMob("clip.wav"); f.content.mobs.append(src)
    desc = f.create.PCMDescriptor()
    for k, v in (("SampleRate", 48000), ("AudioSamplingRate", 48000), ("Channels", 1), ("QuantizationBits", 24), ("BlockAlign", 3), ("AverageBPS", 144000), ("Length", 48000)):
        desc[k].value = v
    desc["ContainerFormat"].value = f.dictionary.lookup_containerdef("AAF")
    src.descriptor = desc
    slot = src.create_empty_slot(edit_rate=48000, media_kind="sound"); slot.segment.length = 48000
    master = f.create.MasterMob("clip"); f.content.mobs.append(master)
    mslot = master.create_timeline_slot(48000)
    mslot.segment = f.create.SourceClip(media_kind="sound"); mslot.segment.mob = src; mslot.segment.slot = slot; mslot.segment.length = 48000
    cslot = comp.create_timeline_slot(48000); seq = f.create.Sequence(media_kind="sound"); cslot.segment = seq
    clip = f.create.SourceClip(media_kind="sound"); clip.mob = master; clip.slot = mslot; clip.length = 48000; seq.components.append(clip)
    tc = comp.create_timeline_slot(edit_rate=25); tc.segment = f.create.Timecode(fps=25, drop=False, length=1000)
    ext = f.create.SourceMob("ext.wav"); f.content.mobs.append(ext)
    edesc = f.create.PCMDescriptor()
    for k, v in (("SampleRate", 48000), ("AudioSamplingRate", 48000), ("Channels", 1), ("QuantizationBits", 24), ("BlockAlign", 3), ("AverageBPS", 144000), ("Length", 48000)):
        edesc[k].value = v
    edesc["ContainerFormat"].value = f.dictionary.lookup_containerdef("External"); ext.descriptor = edesc
    f.dictionary.lookup_datadef("DescriptiveMetadata")

with aaf2.open(ref, "r") as f:
    cfb = f.cfb
    def ser(entry):
        b = bytearray(); name = entry.name.encode("utf-8")
        if entry.isdir():
            b += struct.pack("<BH", 1, len(name)) + name + entry.class_id.bytes_le
            kids = list(entry.listdir()); b += struct.pack("<I", len(kids))
            for k in kids: b += ser(k)
        else:
            data = entry.open().read(); b += struct.pack("<BH", 2, len(name)) + name + struct.pack("<I", len(data)) + data
        return bytes(b)
    blob = ser(cfb.find("/MetaDictionary-1")) + ser(cfb.find("/Header-2/Dictionary-3b04"))
    refprops = cfb.open("/referenced properties").read()
    # The table must be the four paths AafWriter.h expects, in this order.
    order = refprops[0]; count = struct.unpack("<H", refprops[1:3])[0]
    assert count == 4, "referenced properties table changed: update RefPath in AafWriter.h (%d paths)" % count
    pids = struct.unpack("<%dH" % ((len(refprops) - 5) // 2), refprops[5:])
    paths, cur = [], []
    for pid in pids:
        if pid == 0: paths.append(cur); cur = []
        else: cur.append(pid)
    paths = [p for p in paths if p]
    assert [p[-1] for p in paths] == [0x0003, 0x0004, 0x2605, 0x2608], "referenced properties order changed: %r" % paths
    gz = gzip.compress(blob, 9)
    with open(dest, "w") as o:
        o.write("// Generated by tools/gen_aaf_dictionary.py from a pyaaf2 (MIT) reference file:\n// the AAF MetaDictionary and Dictionary subtrees (standard class, property,\n// type, data and container definitions) as gzip'd CFB nodes. Do not edit.\n#include \"AafDictionaryData.h\"\n\nnamespace beatmaker::persistence::aaf\n{\nconst unsigned char dictionaryGz[] = {\n")
        for i in range(0, len(gz), 24): o.write("    " + ",".join("0x%02x" % c for c in gz[i:i+24]) + ",\n")
        o.write("};\nconst unsigned int dictionaryGzSize = %d;\nconst unsigned char referencedProperties[] = { %s };\nconst unsigned int referencedPropertiesSize = %d;\n}\n" % (len(gz), ",".join("0x%02x" % c for c in refprops), len(refprops)))
    print("wrote", dest, "raw", len(blob), "gz", len(gz), "referenced properties", len(refprops))
